W books
DIOLINK/react-app-WBook pull request #1
Opened 2019-10-08 15:17 UTC by DIOLINK

Podrías revisar como voy con el proyecto, en estos momentos me encuentro creando el filtrado para los  libros ya tengo creado algunos de los layouts de la pagina.

2019-10-08 15:33 UTC, adrianponce89 requested changes
Bastante bien! te marque algunas cosas pequeñas. otras te las voy a ir indicando para los proximos PRs

2019-10-08 15:33 UTC, adrianponce89 commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById('root'));
Los archivos siempre tienen que tener una linea extra al final. La ultima linea tiene que ser una vacia

2019-10-08 15:33 UTC, adrianponce89 commented on src/pages/home/book/loyout.js
> +  render() {
Elegí una convención y mantenela durante todo el proyecto. O usas 2 espacios como acá, o 4 espacios como en el resto del proyecto

2019-10-08 15:33 UTC, adrianponce89 commented on src/pages/home/searchbar/layout.js
> +            </div>
Organiza esta seccion de codigo para que tenga la correcta indentación

2019-10-08 15:33 UTC, adrianponce89 commented on src/pages/login/Login.css
> +#login{
Usa espacio antes de {

2019-10-08 15:33 UTC, adrianponce89 commented on src/pages/login/Login.css
> +
No agregues lineas inecesarias luego de comenzar con una {

2019-10-08 15:33 UTC, adrianponce89 commented on src/pages/home/book/loyout.js
> +        <img src={this.props.image_url} height="272px" width="191px" />
Crea constantes sobre BookDetail para "39px", "272px" y "191px". Y usa esas constantes, las constantes usan todos nombres en MAYUSCULAS. Por ejemplo:
```
const IMG_BOOK_LOGO_SIZE = "39px";
const IMG_BOOK_HEIGHT = "272px";
const IMG_BOOK_WIDTH = "191px";
```

2019-10-09 17:21 UTC, DIOLINK commented on src/pages/home/book/loyout.js
> +  render() {
Utilizo entonces el criterio de la extensión de Prettier jejeje

2019-10-09 18:29 UTC, adrianponce89 commented on src/pages/home/book/loyout.js
> +        <img src={this.props.image_url} height="272px" width="191px" />
@DIOLINK

2019-10-10 13:00 UTC, adrianponce89 approved these changes
Bien hecho! Si esta todo funcionando podes presionar en el botón verde de abajo de todo que dice "Merge Pull request", lo que hace es poner tus cambios aprovados en master

2019-10-11 15:56 UTC, DIOLINK commented
Ya repare todo lo que tenia e implemente las correcciones que me sugeriste también genere el Filtro :dango:

2019-10-14 19:13 UTC, merged